kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: worker
  labels:
    node-role: worker-1
- role: worker
  labels:
    node-role: worker-2
- role: worker
  labels:
    node-role: worker-3